"""Haak Anvil CLI — entry point for `haak-anvil` shell command."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from rich.table import Table

from haak_anvil import __version__
from haak_anvil.core.engagement import Engagement
from haak_anvil.core.models import ReportBundle
from haak_anvil.parsers import NessusParser, NmapParser
from haak_anvil.renderers import get_renderer

app = typer.Typer(
    name="haak-anvil",
    help="Modern multi-format pentest report generator. "
    "https://github.com/alancontreras-mx/haak-anvil",
    no_args_is_help=True,
    add_completion=False,
)
console = Console()


def _load_engagement(path: Path | None) -> Engagement:
    if path is None:
        # Anonymous engagement for ad-hoc runs
        return Engagement(
            id="adhoc",
            client_name="Anonymous",
            scope="Ad-hoc parse",
            analyst="Haak Cybersecurity Consulting",
        )
    return Engagement.from_yaml(path)


def _print_summary(bundle: ReportBundle) -> None:
    t = Table(title=f"Report — {bundle.engagement.id}", show_header=True)
    t.add_column("Severity", style="bold")
    t.add_column("Count", justify="right")
    palette = {
        "critical": "red",
        "high": "orange1",
        "medium": "yellow",
        "low": "blue",
        "info": "white",
    }
    for sev, count in bundle.severity_breakdown.items():
        t.add_row(f"[{palette[sev]}]{sev.upper()}[/]", str(count))
    console.print(t)
    console.print(
        f"  [bold]Assets:[/] {len(bundle.assets)}   "
        f"[bold]Findings:[/] {len(bundle.findings)}"
    )


# --------------------------------------------------------------------- commands


@app.command()
def version() -> None:
    """Print Haak Anvil version."""
    console.print(f"haak-anvil {__version__}")


@app.command()
def nmap(
    input: Annotated[Path, typer.Argument(help="Nmap XML file (-oX output)")],
    engagement: Annotated[
        Path | None,
        typer.Option("--engagement", "-e", help="engagement.yaml path"),
    ] = None,
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="Output file (extension determines format)"),
    ] = None,
    format: Annotated[
        str,
        typer.Option("--format", "-f", help="json | md | html"),
    ] = "json",
) -> None:
    """Parse Nmap XML and render a report."""
    eng = _load_engagement(engagement)
    bundle = NmapParser(eng).parse(input)
    _print_summary(bundle)
    _emit(bundle, format=format, output=output)


@app.command()
def nessus(
    input: Annotated[Path, typer.Argument(help=".nessus v2 file")],
    engagement: Annotated[
        Path | None,
        typer.Option("--engagement", "-e", help="engagement.yaml path"),
    ] = None,
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o"),
    ] = None,
    format: Annotated[
        str,
        typer.Option("--format", "-f", help="json | md | html"),
    ] = "json",
) -> None:
    """Parse Nessus .nessus v2 and render a report."""
    eng = _load_engagement(engagement)
    bundle = NessusParser(eng).parse(input)
    _print_summary(bundle)
    _emit(bundle, format=format, output=output)


@app.command()
def merge(
    inputs: Annotated[
        list[Path],
        typer.Argument(help="JSON bundles previously generated by haak-anvil"),
    ],
    engagement: Annotated[
        Path | None,
        typer.Option("--engagement", "-e"),
    ] = None,
    output: Annotated[Path | None, typer.Option("--output", "-o")] = None,
    format: Annotated[str, typer.Option("--format", "-f")] = "json",
) -> None:
    """Merge multiple haak-anvil JSON bundles into one report."""
    if len(inputs) < 2:
        raise typer.BadParameter("merge requires at least 2 input bundles")

    bundles = [ReportBundle.model_validate_json(p.read_text(encoding="utf-8")) for p in inputs]
    merged = bundles[0]
    for b in bundles[1:]:
        merged = merged.merge(b)
    if engagement is not None:
        merged = ReportBundle(
            engagement=_load_engagement(engagement),
            assets=merged.assets,
            findings=merged.findings,
        )
    _print_summary(merged)
    _emit(merged, format=format, output=output)


# --------------------------------------------------------------------- helpers


def _emit(bundle: ReportBundle, *, format: str, output: Path | None) -> None:
    renderer = get_renderer(format)()
    if output is None:
        console.print(renderer.render(bundle))
        return
    written = renderer.write(bundle, output)
    console.print(f"[green]✓[/] Wrote {written}")


if __name__ == "__main__":
    app()
